name: speconn_runtime_dart
description: Dart runtime for Speconn RPC
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.0
  specodec:
    git:
      url: https://github.com/specodec/specodec-dart.git
      ref: v0.0.1